/* Familien-Lernpilot v1.0 – static, rule-based release. No network requests. */
const APP_VERSION = '1.0.0';
const STORAGE_KEY = 'familien-lernpilot-static-v1';
const STATUS = {
  independent: { label: 'selbstständig', description: 'ohne inhaltliche Lösungshilfe' },
  supported: { label: 'mit Hilfe', description: 'mit Hinweis und eigenem Anteil' },
  difficult: { label: 'noch schwierig', description: 'versucht; Ziel noch nicht erreicht' },
  skipped: { label: 'nicht bearbeitet', description: 'ausgelassen; kein Fehler' },
};

const WEEK_INFO = [
  { id: 1, title: 'Woche 1', focus: 'Kennenlernen' },
  { id: 2, title: 'Woche 2', focus: 'Hilfen erproben' },
  { id: 3, title: 'Woche 3', focus: 'Anwenden' },
  { id: 4, title: 'Woche 4', focus: 'Wiedersehen & Rückblick' },
];

const TASKS = [
  { id:'T01', week:1, unit:'A', title:'Eine Zahl sichtbar machen', goal:'tens-ones', step:'tens-ones-14', domain:'Mathematik', material:'14 Plättchen, Bauklötze oder ähnliche Gegenstände', instruction:'Lege die Zahl 14. Kannst du sie so ordnen, dass man einen Zehner und die übrigen Einer sieht? Wie viele Zehner und Einer sind es?', answer:'1 Zehner und 4 Einer. Zeigen, sprechen oder zeichnen ist möglich.', help:{ de:'Zuerst selbst probieren lassen. Hinweis 1: «Kannst du zehn zusammenlegen?» Hinweis 2: Einen Platz für den Zehner und einen für die Einer markieren, aber nicht fertig auslegen.', pt:'Peça que ela represente 14 com tampinhas ou blocos. Deixe-a tentar primeiro. Se precisar, pergunte: “Você consegue juntar dez?” Depois, reserve um espaço para o grupo de dez e outro para as unidades, sem montar tudo por ela. A resposta é uma dezena e quatro unidades.' }, predecessor:'T01-small', next:'T01-16' },
  { id:'T02', week:1, unit:'B', title:'Eine Plusaufgabe lösen', goal:'addition-transition', step:'addition-8-5', domain:'Mathematik', material:'Plättchen oder ein vertrautes Zwanzigerfeld', instruction:'Rechne 8 + 5. Zeige, wie du darauf kommst.', answer:'13. Ein möglicher Weg ist 8 + 2 + 3; andere korrekte Wege gelten ebenfalls.', help:{ de:'Nur bei passender Vorerfahrung: «Wie viel fehlt von acht bis zehn?» Danach: «Teile die fünf so auf, dass du zuerst zehn erreichst.» Keine andere Schulmethode verlangen.', pt:'Deixe que ela resolva 8 + 5 do jeito que conhece. O resultado é 13. Se essa estratégia já fizer sentido para ela, pergunte quanto falta de oito até dez. Depois, ajude a separar o cinco em dois e três. Não exija uma estratégia diferente da usada na escola.' }, predecessor:'T02-6-3', next:'T02-7-5' },
  { id:'T04', week:1, unit:'A', title:'Eine kurze Geschichte verstehen', goal:'reading-comprehension', step:'mila-story', domain:'Lesen', material:'Keines', text:'Mila hat einen roten Ball. Sie legt ihn unter den Tisch. Später holt sie den Ball und geht in den Garten.', instruction:'Welche Farbe hat der Ball? Wo liegt er, bevor Mila ihn holt? Zeige die passende Stelle im Text.', answer:'Rot; unter dem Tisch. Lesedurchführung und Textverständnis getrennt beobachten.', help:{ de:'Erst selbst lesen lassen. Hinweis 1: Nur den betreffenden Satz erneut ansehen. Hinweis 2: Ein unbekanntes Wort erklären oder den betreffenden Satz vorlesen. Vollständiges Vorlesen ist kein Nachweis für selbstständiges Lesen.', pt:'Mila tem uma bola vermelha. Ela a coloca debaixo da mesa. Mais tarde, pega a bola e vai para o jardim. As respostas são: vermelha e debaixo da mesa. Primeiro, deixe que ela leia em alemão. Se você ler ou traduzir o texto, registre essa ajuda; compreender a história ouvida não é o mesmo que lê-la sozinha.' }, predecessor:'T04-short', next:'T04-noah' },
  { id:'T05', week:1, unit:'B', title:'Eine eigene Mitteilung schreiben', goal:'writing-message', step:'one-sentence', domain:'Schreiben', material:'Papier und Stift oder Tastatur', instruction:'Schreibe einen Satz darüber, was du nach der Schule gern machen möchtest.', answer:'Ein verständlicher eigener Satz genügt, zum Beispiel: «Ich möchte im Garten spielen.» Nicht gleichzeitig Rechtschreibung, Handschrift und Zeichensetzung bewerten.', help:{ de:'Zuerst den Satz sagen lassen. Bei Bedarf den Satzanfang «Ich möchte …» anbieten. Wenn ein Erwachsener schreibt, nur die mündliche Formulierung beobachten, nicht selbstständiges Schreiben.', pt:'Peça que ela escreva uma frase sobre o que gostaria de fazer depois da escola. Primeiro, pode falar a frase. Se precisar, ofereça o começo “Ich möchte …”. O objetivo é transmitir uma ideia compreensível, não corrigir tudo de uma vez. Se você escrever por ela, não registre isso como escrita independente.' }, predecessor:null, next:'T05-two-sentences' },
  { id:'T06', week:1, unit:'C', title:'Einkauf spielen', goal:'money-remainder', step:'4-3-of-10', domain:'Alltag', material:'Spielmünzen oder beschriftete Papierstücke', instruction:'Im Spiel kostet ein Heft 4 Franken und ein Stift 3 Franken. Du hast 10 Franken. Wie viel kosten beide zusammen? Wie viel bleibt übrig?', answer:'Zusammen 7 Franken; 3 Franken bleiben. Die Preise sind erfundene Spielpreise.', help:{ de:'«Lege zuerst das Geld für beide Dinge hin.» Danach: «Vergleiche mit deinen zehn Franken. Was bleibt?» Die Anweisung darf vorgelesen werden; ein vorgerechneter Rechenschritt wäre Fachhilfe.', pt:'Nesta brincadeira, o caderno custa quatro francos e o lápis, três. Ela tem dez francos. Os dois custam sete; sobram três. Use dinheiro de brinquedo ou papéis. Se precisar, peça que separe primeiro o valor dos dois objetos e depois veja quanto sobra.' }, predecessor:'T06-small', next:'T06-4-2' },
  { id:'T08', week:1, unit:'freiwillig', title:'Freiwilliges Englischspiel', goal:'english-interest', step:'colours', domain:'Englisch · freiwillig', material:'Gegenstände in der Umgebung', instruction:'Möchtest du drei Farben auf Englisch entdecken? Red heisst rot, blue heisst blau, green heisst grün. Suche etwas Blaues. Du kannst danach sagen: «I like blue.»', answer:'Ein blauer Gegenstand passt zu «blue». Nachsprechen ist freiwillig und kein Aussprachetest.', help:{ de:'Nur so viele Wörter aufnehmen, wie das Kind möchte. Nicht gewähltes Englisch verändert keine Mathe- oder Deutschplanung.', pt:'Pergunte se ela quer brincar com cores em inglês. Red é vermelho, blue é azul e green é verde. Ela pode procurar algo azul e, se quiser, dizer “I like blue”. Não é uma prova de pronúncia. Parar ou não participar não conta como erro.' }, predecessor:null, next:null, optional:true },
  { id:'T03', week:2, unit:'B', title:'Wegnehmen und erklären', goal:'subtraction-material', step:'13-minus-5', domain:'Mathematik', material:'13 Plättchen', instruction:'Du hast 13 Plättchen. Nimm 5 weg. Wie viele bleiben? Zeige deinen Weg.', answer:'8. Der verlangte Materialgebrauch ist keine zusätzliche Hilfe.', help:{ de:'«Zeige zuerst, welche Plättchen du wegnimmst.» Wenn vertraut: «Du kannst erst drei und dann noch zwei wegnehmen.» Ergebnis nicht vorwegnehmen.', pt:'Separe 13 peças e peça que ela retire cinco. Devem sobrar oito. Deixe-a mostrar como pensou. Se precisar, ajude a identificar quais peças serão retiradas. Outra possibilidade é tirar primeiro três e depois duas, mas não obrigue esse caminho.' }, predecessor:'T03-9-3', next:'T03-14-6' },
  { id:'T07', week:2, unit:'C', title:'Vergleichen und messen', goal:'length-comparison', step:'compare-two', domain:'Alltag', material:'Zwei unterschiedlich lange Stifte; bei Vertrautheit ein Lineal', instruction:'Welcher Stift ist länger? Lege die Anfänge nebeneinander. Wenn du schon mit Zentimetern misst: Miss beide Stifte und schreibe die Längen auf.', answer:'Die Werte hängen von den verwendeten Stiften ab. Der Vergleich allein kann abgeschlossen sein.', help:{ de:'«Beginnen beide am gleichen Ort?» Beim Messen: «Zeige die Null am Lineal.» Eine vorgezeigte Messung als Hilfe notieren; keine Millimeter voraussetzen.', pt:'Compare dois lápis de tamanhos diferentes, alinhando uma das pontas. Se ela já usa a régua, peça que meça a partir do zero e diga a medida em centímetros. Os valores dependem dos lápis reais; não há um número fixo como resposta. Se você mostrar onde começar, registre a ajuda.' }, predecessor:null, next:'T07-three-items' },
  { id:'T02-6-3', week:2, unit:'A', title:'Plus mit Material – Vorläufer', goal:'addition-transition', step:'addition-small', domain:'Mathematik', material:'Plättchen oder vertrautes Zwanzigerfeld', instruction:'Rechne 6 + 3. Lege oder zeichne deinen Weg.', answer:'9. Diese Aufgabe ist ein kleinerer Schritt, wenn 8 + 5 noch schwierig war.', help:{ de:'Material bereitlegen, dann erst selbst probieren lassen. Keine zusätzliche Aufgabenserie anhängen.', pt:'Deixe o material disponível e deixe-a tentar primeiro. Esta é uma etapa menor, não uma punição nem uma série extra de exercícios.' }, predecessor:null, next:'T02' },
  { id:'T02-7-5', week:3, unit:'A', title:'Plusaufgabe – neue Variante', goal:'addition-transition', step:'addition-7-5', domain:'Mathematik', material:'Plättchen oder ein vertrautes Zwanzigerfeld', instruction:'Rechne 7 + 5. Zeige, wie du darauf kommst.', answer:'12. Eine neue, vergleichbare Aufgabe – kein Beleg für ein allgemeines Können.', help:{ de:'Die bekannte hilfreiche Darstellung beibehalten. Nicht mehrere Schwierigkeitsstufen auf einmal ändern.', pt:'Mantenha a representação que ajudou. Não mude várias coisas ao mesmo tempo.' }, predecessor:'T02-6-3', next:null },
  { id:'T04-noah', week:4, unit:'A', title:'Neue kurze Geschichte', goal:'reading-comprehension', step:'noah-story', domain:'Lesen', material:'Keines', text:'Noah hat einen blauen Becher. Er stellt ihn auf die Bank. Später nimmt er den Becher und geht ins Haus.', instruction:'Welche Farbe hat der Becher? Wo steht er, bevor Noah ihn nimmt?', answer:'Blau; auf der Bank. Neue, ähnlich schwierige Aufgabe statt Wiederholen auswendig bekannter Antworten.', help:{ de:'Zuerst selbst lesen lassen. Einen betreffenden Satz erneut ansehen oder bei Bedarf nur ihn vorlesen.', pt:'Deixe que ela leia primeiro. Veja novamente a frase correspondente ou, se precisar, leia apenas essa frase.' }, predecessor:'T04-short', next:null },
  { id:'T01-16', week:4, unit:'A', title:'Zahl sichtbar machen – neue Variante', goal:'tens-ones', step:'tens-ones-16', domain:'Mathematik', material:'16 Plättchen oder Bauklötze', instruction:'Lege die Zahl 16. Ordne sie so, dass man einen Zehner und die übrigen Einer sieht.', answer:'1 Zehner und 6 Einer. Eine parallele neue Zahl, kein Test.', help:{ de:'Dieselbe Darstellungsform wie zuvor verwenden. Erst bei bestätigtem Unterrichtsanschluss einen neuen Zahlenraum wählen.', pt:'Use a mesma forma de representação de antes. Só mude a faixa numérica quando houver ligação confirmada com a aula.' }, predecessor:'T01-small', next:null },
  { id:'T01-small', week:2, unit:'A', title:'Mengen bis 10 vergleichen', goal:'tens-ones', step:'quantities-to-10', domain:'Mathematik', material:'Bis zu 10 Plättchen', instruction:'Lege 6 Plättchen und dann 8 Plättchen. Welche Menge ist grösser? Zeige sie.', answer:'8 ist grösser. Ein Vorläufer für die Zahlendarstellung mit Zehnern.', help:{ de:'Mengen deutlich getrennt legen. Nicht sofort den Zehner erklären.', pt:'Coloque as quantidades separadas e visíveis. Não explique a dezena imediatamente.' }, predecessor:null, next:'T01' },
  { id:'T04-short', week:2, unit:'A', title:'Eine sehr kurze Aussage verstehen', goal:'reading-comprehension', step:'short-sentence', domain:'Lesen', material:'Keines', text:'Der Ball ist rot.', instruction:'Welche Farbe hat der Ball?', answer:'Rot. Ein kleinerer Textumfang, wenn die Geschichte noch schwierig war.', help:{ de:'Den Satz zeigen und bei Bedarf einmal vorlesen. Verstehen und selbst lesen getrennt notieren.', pt:'Mostre a frase e, se preciso, leia uma vez. Registre separadamente compreender e ler de forma independente.' }, predecessor:null, next:'T04' },
  { id:'T03-9-3', week:2, unit:'B', title:'Wegnehmen mit Material – Vorläufer', goal:'subtraction-material', step:'9-minus-3', domain:'Mathematik', material:'9 Plättchen', instruction:'Du hast 9 Plättchen. Nimm 3 weg. Wie viele bleiben?', answer:'6. Vorläufer, falls 13 − 5 noch schwierig war.', help:{ de:'Die wegzunehmenden Plättchen zeigen lassen, ohne das Ergebnis zu sagen.', pt:'Peça que ela mostre as peças que vai tirar, sem dizer o resultado.' }, predecessor:null, next:'T03' },
  { id:'T03-14-6', week:3, unit:'B', title:'Wegnehmen – neue Variante', goal:'subtraction-material', step:'14-minus-6', domain:'Mathematik', material:'14 Plättchen', instruction:'Du hast 14 Plättchen. Nimm 6 weg. Wie viele bleiben?', answer:'8. Eine neue, vergleichbare Aufgabe.', help:{ de:'Eine bekannte Darstellung verwenden, keine neue Rechenmethode einführen.', pt:'Use uma representação conhecida; não introduza um novo método de cálculo.' }, predecessor:'T03-9-3', next:null },
  { id:'T06-small', week:2, unit:'C', title:'Kleiner Einkauf', goal:'money-remainder', step:'2-1-of-5', domain:'Alltag', material:'Spielmünzen oder Papierstücke', instruction:'Im Spiel kosten zwei Dinge 2 Franken und 1 Franken. Du hast 5 Franken. Wie viel bleibt übrig?', answer:'2 Franken bleiben.', help:{ de:'Zuerst die beiden Preise legen, dann mit 5 Franken vergleichen.', pt:'Primeiro, separe os dois preços; depois compare com os 5 francos.' }, predecessor:null, next:'T06' },
  { id:'T06-4-2', week:3, unit:'C', title:'Einkauf – neue Variante', goal:'money-remainder', step:'4-2-of-10', domain:'Alltag', material:'Spielmünzen oder Papierstücke', instruction:'Im Spiel kosten zwei Dinge 4 Franken und 2 Franken. Du hast 10 Franken. Wie viel bleibt übrig?', answer:'4 Franken bleiben.', help:{ de:'Bekanntes Material verwenden; keine zusätzlichen Produkte oder Rappenbeträge hinzufügen.', pt:'Use o material já conhecido; não acrescente produtos extras ou valores em cêntimos.' }, predecessor:'T06-small', next:null },
  { id:'T05-two-sentences', week:4, unit:'B', title:'Eine kurze Mitteilung schreiben', goal:'writing-message', step:'two-sentences', domain:'Schreiben', material:'Papier und Stift oder Tastatur', instruction:'Schreibe eine kurze Mitteilung mit ein oder zwei Sätzen, zum Beispiel für eine Einkaufsnotiz.', answer:'Eine verständliche eigene Mitteilung zählt. Nur eine Anforderung gegenüber dem ersten Satz verändern.', help:{ de:'Erst die Nachricht mündlich planen. Bei Bedarf einen Satzanfang anbieten, nicht den ganzen Text diktieren.', pt:'Plane a mensagem oralmente primeiro. Se precisar, ofereça o início de uma frase, mas não dite o texto inteiro.' }, predecessor:null, next:null },
  { id:'T07-three-items', week:4, unit:'C', title:'Drei Gegenstände ordnen', goal:'length-comparison', step:'compare-three', domain:'Alltag', material:'Drei unterschiedlich lange Gegenstände', instruction:'Ordne drei Gegenstände von kurz nach lang.', answer:'Die Reihenfolge hängt von den Gegenständen ab. Messen ist weiterhin freiwillig und nur bei Vertrautheit.', help:{ de:'Anfänge nebeneinander legen und zunächst nur vergleichen.', pt:'Alinhe uma das pontas e compare primeiro, sem medir obrigatoriamente.' }, predecessor:null, next:null },
];

// Optionales Unterstützungsmodul. Es ist kein verbindlicher Wochenauftrag und steuert keine automatische Niveauänderung.
const NUMBER_TASKS = [
  { id:'N01', title:'Punktebild zählen', goal:'numbers-points-1-100', step:'points-as-tens', domain:'Zahlen 1–100 · optional', material:'Keines', instruction:'Zähle die Punkte. Du darfst zuerst die Zehnergruppen und danach die übrigen Punkte zählen. Welche Zahl passt?', answer:'24. Die Punkte sind als zwei volle Zehnergruppen und vier weitere Punkte sichtbar.', help:{ de:'Zeit zum Schauen geben. Frage höchstens: «Siehst du Gruppen mit zehn Punkten?» Nicht sofort vorsagen. Bei Anstrengung reicht es, eine Gruppe zu zeigen oder eine Pause zu machen.', pt:'Dê tempo para olhar. Pergunte no máximo: “Você vê grupos de dez pontos?” Não diga a resposta logo. Se ficar cansativo, basta mostrar um grupo ou fazer uma pausa.' }, activity:{ kind:'dots', count:24, choices:[22,24,26] } },
  { id:'N02', title:'Zahlenkarte finden', goal:'numbers-match-1-100', step:'number-card', domain:'Zahlen 1–100 · optional', material:'Keines', instruction:'Finde die Zahlenkarte 43.', answer:'43. Hier wird nur das Wiedererkennen dieser Zahlenkarte beobachtet, nicht ein allgemeines Können im Zahlenraum.', help:{ de:'Die drei Karten ruhig anschauen lassen. Du kannst die Zahl vorlesen, wenn das Lesen der Ziffern nicht das Ziel sein soll. Bei Unsicherheit darf sie auf eine Karte zeigen und später noch einmal schauen.', pt:'Deixe que ela olhe as três cartas com calma. Você pode ler o número se reconhecer os algarismos não for o objetivo. Em caso de dúvida, ela pode apontar uma carta e olhar de novo depois.' }, activity:{ kind:'choice', target:43, choices:[34,43,45] } },
  { id:'N03', title:'Eine Zahl in der Reihe', goal:'numbers-order-1-100', step:'next-number', domain:'Zahlen 1–100 · optional', material:'Keines', instruction:'Welche Zahl kommt nach 58?', answer:'59. Es ist eine einzelne Reihenfolgefrage, keine Zeitaufgabe.', help:{ de:'Sie darf die Reihe mit dem Finger mitdenken oder die Zahlen laut sagen. Keine Eile und keine zusätzlichen Reihen anhängen.', pt:'Ela pode acompanhar a sequência com o dedo ou dizer os números em voz alta. Sem pressa e sem acrescentar outras sequências.' }, activity:{ kind:'sequence', target:59, choices:[57,58,59] } },
];

// Nur bereits vorhandene Aufgaben und Varianten; die Druckansicht ergänzt keinen eigenen Kurs.
const WEEK_PRINT_TASK_IDS = {
  1: ['T01', 'T04', 'T05', 'T02', 'T06', 'T08'],
  2: ['T02-6-3', 'T04', 'T05', 'T03', 'T07', 'T08'],
  3: ['T02-7-5', 'T05', 'T03-14-6', 'T06-4-2', 'T08'],
  4: ['T01-16', 'T04-noah', 'T05-two-sentences', 'T07-three-items'],
};

const state = { activeWeek:1, selectedTaskId:'T01', selectedNumberTaskId:'N01', helpLanguage:'de', selectedStatus:null, selectedNumberStatus:null, data:null };
const $ = (selector) => document.querySelector(selector);
const tasksForWeek = () => TASKS.filter((task) => task.week === state.activeWeek && !task.id.includes('-small') && !task.id.includes('-6-3') && !task.id.includes('-7-5') && !task.id.includes('-noah') && !task.id.includes('-16') && !task.id.includes('-14-6') && !task.id.includes('-4-2') && !task.id.includes('two-sentences') && !task.id.includes('three-items') && !task.id.includes('short'));
const taskById = (id) => TASKS.find((task) => task.id === id) || NUMBER_TASKS.find((task) => task.id === id);
const numberTaskById = (id) => NUMBER_TASKS.find((task) => task.id === id);
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone:'Europe/Zurich' }).format(new Date());

function newData() { return { schema:'familien-lernpilot-static', version:APP_VERSION, exportedAt:null, activeProfileId:'pilot', profiles:[{ id:'pilot', displayName:'Pilotprofil (leer)', observations:[] }] }; }
function loadData() { try { const saved = localStorage.getItem(STORAGE_KEY); return saved ? validateData(JSON.parse(saved)) : newData(); } catch { return newData(); } }
function saveData() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.data)); setStorageStatus('Im Browser gespeichert – bitte vor dem Schliessen exportieren.'); } catch { setStorageStatus('Speichern im Browser nicht verfügbar. Exportiere die Daten manuell.', true); } }
function validateData(data) { if (!data || data.schema !== 'familien-lernpilot-static' || !Array.isArray(data.profiles)) throw new Error('Unbekannte Exportdatei.'); data.profiles.forEach((profile) => { if (!profile.id || !Array.isArray(profile.observations)) throw new Error('Unvollständige Exportdatei.'); }); return data; }
function profile() { return state.data.profiles.find((item) => item.id === state.data.activeProfileId) || state.data.profiles[0]; }
function setStorageStatus(message, error=false) { const target = $('#storage-status'); if (target) { target.textContent = message; target.classList.toggle('error', error); } }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char])); }

function renderProfileSelect() { $('#profile-select').innerHTML = state.data.profiles.map((item) => `<option value="${item.id}">${escapeHtml(item.displayName)}</option>`).join(''); $('#profile-select').value = profile().id; }
function renderWeeks() { $('#week-picker').innerHTML = WEEK_INFO.map((week) => `<button class="week-button ${week.id===state.activeWeek?'is-selected':''}" data-week="${week.id}" type="button"><strong>${week.title}</strong><small>${week.focus}</small></button>`).join(''); $('#week-picker').querySelectorAll('[data-week]').forEach((button) => button.addEventListener('click', () => { state.activeWeek = Number(button.dataset.week); const available = tasksForWeek(); state.selectedTaskId = available[0]?.id || 'T01'; renderTasks(); })); }
function renderTasks() { renderWeeks(); const tasks = tasksForWeek(); $('#task-count').textContent = `${tasks.length} angebotene Aufgaben${state.activeWeek===1?' + Englisch freiwillig':''}`; $('#task-list').innerHTML = tasks.map((task) => `<button class="task-choice ${task.id===state.selectedTaskId?'is-selected':''}" data-task="${task.id}" type="button"><strong>${escapeHtml(task.title)}</strong><span>${escapeHtml(task.domain)} · Einheit ${task.unit}</span></button>`).join(''); $('#task-list').querySelectorAll('[data-task]').forEach((button) => button.addEventListener('click', () => { state.selectedTaskId = button.dataset.task; state.selectedStatus = null; renderTasks(); })); renderTaskCard(); }

function printTasksForWeek() { return (WEEK_PRINT_TASK_IDS[state.activeWeek] || []).map(taskById).filter(Boolean); }
function printTaskMarkup(task, index) {
  return `<article class="print-task"><p class="print-task-id">Aufgabe ${index + 1} · ${escapeHtml(task.id)}</p><h2>${escapeHtml(task.title)}</h2>${task.text ? `<p class="print-story">${escapeHtml(task.text)}</p>` : ''}<p><strong>Arbeitsauftrag:</strong> ${escapeHtml(task.instruction)}</p><p class="print-material"><strong>Du kannst benutzen:</strong> ${escapeHtml(task.material)}</p><div class="print-work-space"><span>Meine Zeichnung oder Notiz:</span></div></article>`;
}
function adultPrintMarkup(task, language, index) {
  return `<article class="print-adult-card"><p class="print-task-id">Aufgabe ${index + 1} · ${escapeHtml(task.id)}</p><h2>${escapeHtml(task.title)}</h2><p>${escapeHtml(task.help[language])}</p></article>`;
}
function renderPrintSheet(preview=true) {
  const week = WEEK_INFO.find((item) => item.id === state.activeWeek); const tasks = printTasksForWeek(); const includeAdult = $('#include-adult-help').checked; const language = $('#print-help-language').value; const sheet = $('#print-sheet');
  sheet.classList.toggle('is-preview', preview);
  sheet.innerHTML = `<section class="print-child-page"><div class="print-header"><p class="print-kicker">Familien-Lernpilot · ${escapeHtml(week?.title || 'Woche')}</p><h1>${escapeHtml(week?.focus || 'Wochenblatt')}</h1><p>Wähle eine kurze Einheit. Du musst nicht alles machen. Wenn es schwierig wird, darfst du Pause machen oder Hilfe holen.</p></div>${tasks.map(printTaskMarkup).join('')}<p class="print-footer">Generisches Übungsangebot · kein bestätigter Unterrichtsanschluss · Aufgaben auf Papier nur einmal als Papierbearbeitung eintragen.</p></section>${includeAdult ? `<section class="print-adult-page"><div class="print-header"><p class="print-kicker">Begleithinweise · ${language === 'pt' ? 'Português (BR)' : 'Deutsch'}</p><h1>${escapeHtml(week?.title || 'Woche')}</h1><p>Diese separate Seite ist für Erwachsene. Sie enthält die vorgesehenen Hilfen und gegebenenfalls Lösungshinweise, nie neben dem Kinderblatt.</p></div>${tasks.map((task, index) => adultPrintMarkup(task, language, index)).join('')}</section>` : ''}<div class="print-preview-actions"><button id="close-print-preview" class="button secondary" type="button">Vorschau schliessen</button></div>`;
  sheet.querySelector('#close-print-preview')?.addEventListener('click', () => { sheet.classList.remove('is-preview'); sheet.innerHTML=''; });
  if (preview) sheet.scrollIntoView({ behavior:'smooth', block:'start' });
}
function printWeek() {
  renderPrintSheet(false);
  if (typeof window.print === 'function') { $('#print-sheet').dataset.printMode = 'native'; window.print(); return; }
  const sheet = $('#print-sheet'); sheet.classList.add('is-preview');
  sheet.dataset.printMode = 'preview-fallback';
  sheet.querySelector('.print-preview-actions')?.insertAdjacentHTML('afterbegin', '<p class="print-dialog-note" role="status">Dieser eingebettete Browser stellt keinen Druckdialog bereit. Die Vorschau ist vorbereitet: Bitte in einem normalen Desktop-Browser über „Drucken“ bzw. Strg+P fortfahren.</p>');
}

function renderTaskCard() {
  const task = taskById(state.selectedTaskId); if (!task) return;
  const help = task.help[state.helpLanguage];
  $('#task-card').innerHTML = `
    <span class="badge">Generisches Übungsangebot · kein bestätigter Unterrichtsanschluss</span>
    <h2>${escapeHtml(task.title)}</h2>
    <p class="quiet">${escapeHtml(task.domain)} · Lernziel: ${escapeHtml(task.goal)} · Aufgaben-ID ${task.id}</p>
    ${task.text ? `<p class="task-text">${escapeHtml(task.text)}</p>` : ''}
    <p class="task-instruction">${escapeHtml(task.instruction)}</p>
    <p class="materials"><strong>Material:</strong> ${escapeHtml(task.material)}</p>
    <details><summary>Beobachtungskriterium für Erwachsene</summary><p>${escapeHtml(task.answer)}</p></details>
    <section class="help-box"><div class="help-toggle"><strong>Erwachsenenhilfe</strong><div class="language-toggle" aria-label="Sprache der Erwachsenenhilfe"><button class="${state.helpLanguage==='de'?'is-active':''}" data-language="de" type="button">Deutsch</button><button class="${state.helpLanguage==='pt'?'is-active':''}" data-language="pt" type="button">Português (BR)</button></div></div><p class="help-content">${escapeHtml(help)}</p></section>
    <form id="record-form" class="record-form"><h3>Ergebnis festhalten</h3><p class="quiet">Der Status beschreibt nur diese Aufgabe und wird von einer begleitenden erwachsenen Person gewählt.</p><div class="status-grid">${Object.entries(STATUS).map(([key, value]) => `<button class="status-button ${state.selectedStatus===key?'is-selected':''}" data-status="${key}" type="button">${value.label}<small>${value.description}</small></button>`).join('')}</div><div class="form-row"><label>Bearbeitungsdatum<input id="observation-date" type="date" value="${today()}" required></label><label>Eingabequelle<select id="source"><option value="browser">Browser</option><option value="papier">Papier</option><option value="muendlich">Mündliche Antwort</option><option value="material">Materialhandlung</option></select></label></div><label class="note-label">Hilfen / kurze Beobachtung (optional)<textarea id="note" maxlength="500" placeholder="z. B. Plättchen bereitgelegt; Anweisung vorgelesen"></textarea></label><div class="button-row"><button class="button" type="submit">Beobachtung speichern</button></div><p id="form-message" class="form-message" role="status"></p></form>`;
  $('#task-card').querySelectorAll('[data-language]').forEach((button) => button.addEventListener('click', () => { state.helpLanguage = button.dataset.language; renderTaskCard(); }));
  $('#task-card').querySelectorAll('[data-status]').forEach((button) => button.addEventListener('click', () => { state.selectedStatus = button.dataset.status; renderTaskCard(); }));
  $('#record-form').addEventListener('submit', recordObservation);
}

function numberActivityMarkup(task) {
  const activity = task.activity;
  if (activity.kind === 'dots') {
    return `<div class="number-activity"><p class="child-prompt">Schau in Ruhe. Wie viele Punkte siehst du?</p><div class="dot-picture" role="img" aria-label="Punktebild zum Zählen">${Array.from({ length:activity.count }, (_, index) => `<span class="dot ${index > 0 && index % 10 === 0 ? 'new-ten' : ''}" aria-hidden="true"></span>`).join('')}</div><div class="number-choices" aria-label="Eine Zahl auswählen">${activity.choices.map((choice) => `<button class="number-choice" data-number-choice="${choice}" type="button">${choice}</button>`).join('')}</div></div>`;
  }
  const prompt = activity.kind === 'choice' ? 'Welche Karte passt?' : 'Welche Zahl wählst du?';
  return `<div class="number-activity"><p class="child-prompt">${prompt}</p><div class="number-choices" aria-label="Eine Zahl auswählen">${activity.choices.map((choice) => `<button class="number-choice" data-number-choice="${choice}" type="button">${choice}</button>`).join('')}</div></div>`;
}

function renderNumbers() {
  const task = numberTaskById(state.selectedNumberTaskId) || NUMBER_TASKS[0];
  $('#number-list').innerHTML = NUMBER_TASKS.map((item, index) => `<button class="task-choice ${item.id===task.id?'is-selected':''}" data-number-task="${item.id}" type="button"><strong>${index + 1}. ${escapeHtml(item.title)}</strong><span>kurz und optional</span></button>`).join('');
  $('#number-list').querySelectorAll('[data-number-task]').forEach((button) => button.addEventListener('click', () => { state.selectedNumberTaskId=button.dataset.numberTask; state.selectedNumberStatus=null; renderNumbers(); }));
  const help = task.help[state.helpLanguage];
  $('#numbers-card').innerHTML = `<span class="badge">Generisches Unterstützungsangebot · kein bestätigter Unterrichtsanschluss</span><h2>${escapeHtml(task.title)}</h2><p class="quiet">${escapeHtml(task.domain)} · Aufgaben-ID ${task.id}</p><p class="task-instruction">${escapeHtml(task.instruction)}</p>${numberActivityMarkup(task)}<p class="number-feedback" data-number-feedback role="status">Wähle eine Zahl. Danach kannst du deinen Weg zeigen oder erklären.</p><p class="materials"><strong>Material:</strong> ${escapeHtml(task.material)}</p><details><summary>Beobachtungskriterium für Erwachsene</summary><p>${escapeHtml(task.answer)}</p></details><section class="help-box"><div class="help-toggle"><strong>Erwachsenenhilfe</strong><div class="language-toggle" aria-label="Sprache der Erwachsenenhilfe"><button class="${state.helpLanguage==='de'?'is-active':''}" data-number-language="de" type="button">Deutsch</button><button class="${state.helpLanguage==='pt'?'is-active':''}" data-number-language="pt" type="button">Português (BR)</button></div></div><p class="help-content">${escapeHtml(help)}</p></section><form class="record-form" data-number-form><h3>Beobachtung festhalten</h3><p class="quiet">Der Status gilt nur für diese einzelne Karte. Das optionale Modul verändert die Wochenplanung nicht automatisch.</p><div class="status-grid">${Object.entries(STATUS).map(([key, value]) => `<button class="status-button ${state.selectedNumberStatus===key?'is-selected':''}" data-number-status="${key}" type="button">${value.label}<small>${value.description}</small></button>`).join('')}</div><div class="form-row"><label>Bearbeitungsdatum<input name="number-date" type="date" value="${today()}" required></label><label>Eingabequelle<select name="number-source"><option value="browser">Browser</option><option value="papier">Papier</option><option value="muendlich">Mündliche Antwort</option><option value="material">Materialhandlung</option></select></label></div><label class="note-label">Kurze Beobachtung (optional)<textarea name="number-note" maxlength="500" placeholder="z. B. in Zehnergruppen gezählt"></textarea></label><div class="button-row"><button class="button" type="submit">Beobachtung speichern</button></div><p class="form-message" data-number-message role="status"></p></form>`;
  const card = $('#numbers-card');
  card.querySelectorAll('[data-number-language]').forEach((button) => button.addEventListener('click', () => { state.helpLanguage=button.dataset.numberLanguage; renderNumbers(); }));
  card.querySelectorAll('[data-number-status]').forEach((button) => button.addEventListener('click', () => { state.selectedNumberStatus=button.dataset.numberStatus; renderNumbers(); }));
  card.querySelectorAll('[data-number-choice]').forEach((button) => button.addEventListener('click', () => { card.querySelector('[data-number-feedback]').textContent=`Du hast ${button.dataset.numberChoice} gewählt. Zeige oder erkläre deinen Weg. Wenn du unsicher bist, darfst du noch einmal schauen oder Pause machen.`; }));
  card.querySelector('[data-number-form]').addEventListener('submit', recordNumberObservation);
}

function recordNumberObservation(event) {
  event.preventDefault(); const form=event.currentTarget; const message=form.querySelector('[data-number-message]');
  if (!state.selectedNumberStatus) { message.textContent='Bitte zuerst einen Status wählen.'; message.classList.add('error'); return; }
  const task=numberTaskById(state.selectedNumberTaskId); const date=form.elements['number-date'].value; if (!date) return;
  if (profile().observations.some((item) => item.taskId===task.id && item.date===date)) { message.textContent='Für diese Karte gibt es an diesem Tag bereits eine Beobachtung. Sie wird nicht doppelt gezählt.'; message.classList.add('error'); return; }
  profile().observations.push({ id:crypto.randomUUID(), taskId:task.id, goal:task.goal, step:task.step, date, status:state.selectedNumberStatus, source:form.elements['number-source'].value, note:form.elements['number-note'].value.trim(), recordedAt:new Date().toISOString(), ruleVersion:APP_VERSION });
  saveData(); state.selectedNumberStatus=null; message.textContent='Gespeichert. Das ist eine einzelne Beobachtung, keine Einstufung.'; message.classList.remove('error'); renderParent();
}

function recordObservation(event) {
  event.preventDefault(); const message = $('#form-message'); if (!state.selectedStatus) { message.textContent = 'Bitte zuerst einen Status wählen.'; message.classList.add('error'); return; }
  const task = taskById(state.selectedTaskId); const date = $('#observation-date').value; if (!date) return;
  const existing = profile().observations.find((item) => item.taskId===task.id && item.date===date);
  if (existing) { message.textContent = 'Für diese Aufgabe gibt es an diesem Tag bereits eine Beobachtung. Sie wird nicht doppelt gezählt.'; message.classList.add('error'); return; }
  profile().observations.push({ id:crypto.randomUUID(), taskId:task.id, goal:task.goal, step:task.step, date, status:state.selectedStatus, source:$('#source').value, note:$('#note').value.trim(), recordedAt:new Date().toISOString(), ruleVersion:APP_VERSION });
  saveData(); state.selectedStatus = null; message.textContent = 'Gespeichert. Die Elternübersicht erklärt den nächsten Vorschlag nachvollziehbar.'; message.classList.remove('error'); renderParent();
}

function countedObservations(goal) {
  const usable = profile().observations.filter((item) => item.goal===goal && item.status!== 'skipped').sort((a,b) => a.recordedAt.localeCompare(b.recordedAt));
  const byDay = new Map(); usable.forEach((item) => { if (!byDay.has(item.date)) byDay.set(item.date, item); });
  return [...byDay.values()].sort((a,b) => a.date.localeCompare(b.date)).slice(-3);
}
function taskForGoal(goal) { return TASKS.find((task) => task.goal===goal && !task.id.includes('-small') && !task.id.includes('-6-3') && !task.id.includes('-short')) || TASKS.find((task) => task.goal===goal); }
function recommendationForGoal(goal) {
  const base = taskForGoal(goal); const entries = countedObservations(goal); const recentDifficult = entries.filter((item) => item.status==='difficult'); const recentSupported = entries.filter((item) => item.status==='supported'); const independent = entries.filter((item) => item.status==='independent');
  if (!entries.length) return { goal, base, task:base, rule:'Start', text:'Noch keine verwertbare Beobachtung. Mit einer kurzen bekannten Beispielaufgabe beginnen; Unterrichtsanschluss bleibt offen.' };
  if (recentDifficult.length >= 2 && base?.predecessor) return { goal, base, task:taskById(base.predecessor), rule:'Regel 3', text:'An zwei verschiedenen Tagen war dieser Lernschritt noch schwierig. Die nächste reguläre Aufgabe nutzt einen kleineren Vorläufer oder eine bessere Darstellung – ohne Zusatzpensum.' };
  if (independent.length===3 && base?.next) return { goal, base, task:taskById(base.next), rule:'Regel 4', text:'An drei verschiedenen Tagen wurden vergleichbare Aufgaben selbstständig bearbeitet. Eine einzelne neue Anwendung kann angeboten werden; das ist keine allgemeine Einstufung.' };
  if (recentSupported.length >= 2) return { goal, base, task:base, rule:'Regel 5', text:'In mindestens zwei der letzten Beobachtungstage war Hilfe nützlich. Lernziel und hilfreiche Darstellung bleiben zunächst erhalten.' };
  return { goal, base, task:base, rule:'Regel 6', text:'Gemischte oder einzelne Beobachtung: Lernschritt beibehalten und später eine neue, vergleichbare Aufgabe anbieten.' };
}
function renderParent() {
  const observations = profile().observations.slice().sort((a,b) => b.date.localeCompare(a.date) || b.recordedAt.localeCompare(a.recordedAt)); const goals = [...new Set(TASKS.filter((task) => !task.optional).map((task) => task.goal))];
  $('#parent-summary').innerHTML = goals.map((goal) => { const rec = recommendationForGoal(goal); const seen = countedObservations(goal); return `<article class="summary-card"><p>${escapeHtml(rec.base?.domain || goal)}</p><strong>${escapeHtml(rec.base?.title || goal)}</strong><p>${seen.length ? `${seen.length} verwertbare Beobachtung${seen.length===1?'':'en'} auf unterschiedlichen Tagen` : 'noch zu wenig beobachtet'}</p></article>`; }).join('');
  const recs = goals.map(recommendationForGoal); const priority = recs.find((item) => item.rule==='Regel 3') || recs.find((item) => item.rule==='Regel 5') || recs.find((item) => item.rule==='Regel 4') || recs.find((item) => item.rule==='Start') || recs[0];
  $('#next-task').innerHTML = priority ? `<div class="recommendation"><p><strong>${escapeHtml(priority.task?.title || 'Noch offen')}</strong> <span class="status-tag">${priority.rule}</span></p><p>${escapeHtml(priority.text)}</p><button class="button secondary" data-open-task="${priority.task?.id || ''}" type="button">Aufgabe öffnen</button></div>` : '<p class="empty">Noch keine passende Aufgabe.</p>';
  $('#next-task').querySelector('[data-open-task]')?.addEventListener('click', (event) => { const task = taskById(event.currentTarget.dataset.openTask); if (task) { state.activeWeek=task.week; state.selectedTaskId=task.id; showView('tasks'); renderTasks(); } });
  $('#observation-list').innerHTML = observations.length ? observations.map((item) => { const task = taskById(item.taskId); return `<article class="observation"><strong>${escapeHtml(task?.title || item.taskId)}</strong> <span class="status-tag">${STATUS[item.status]?.label || item.status}</span><br><span class="quiet">${item.date} · ${escapeHtml(item.source)}${item.note ? ` · ${escapeHtml(item.note)}`:''}</span></article>`; }).join('') : $('#empty-state-template').innerHTML;
}
function showView(view) { ['tasks','numbers','parent','data'].forEach((name) => { $(`#${name}-view`).hidden = name!==view; document.querySelector(`[data-view="${name}"]`).classList.toggle('is-active', name===view); }); if (view==='numbers') renderNumbers(); if (view==='parent') renderParent(); if (view==='data') setStorageStatus('Dieser Teststand bleibt in diesem Browser. Export erzeugt eine Übergabedatei; Import ersetzt den bisherigen lokalen Teststand.'); }
function exportData() { const copy = structuredClone(state.data); copy.exportedAt = new Date().toISOString(); const blob = new Blob([JSON.stringify(copy, null, 2)], { type:'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `familien-lernpilot-static-${today()}.json`; link.click(); URL.revokeObjectURL(link.href); setStorageStatus('Übergabedatei erstellt. Bitte nur durch eine erwachsene Person geschützt übertragen.'); }
function importData(event) { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const incoming = validateData(JSON.parse(reader.result)); const currentCount = profile().observations.length; const incomingProfile = incoming.profiles.find((item) => item.id===incoming.activeProfileId) || incoming.profiles[0]; if (!confirm(`Die Übergabedatei enthält ${incomingProfile.observations.length} Beobachtungen und ersetzt die aktuellen ${currentCount} auf diesem Gerät. Fortfahren?`)) return; state.data = incoming; saveData(); renderProfileSelect(); renderTasks(); renderParent(); setStorageStatus('Übergabedatei geprüft und als neuer lokaler Teststand geladen.'); } catch (error) { setStorageStatus(`Import nicht übernommen: ${error.message}`, true); } }; reader.readAsText(file); event.target.value=''; }
function resetData() { if (!confirm('Alle lokalen Beobachtungen dieses Browsers löschen? Bereits exportierte Dateien bleiben erhalten.')) return; state.data = newData(); saveData(); renderProfileSelect(); renderTasks(); renderParent(); setStorageStatus('Lokaler Stand wurde zurückgesetzt.'); }
function init() { state.data=loadData(); renderProfileSelect(); renderTasks(); renderNumbers(); renderParent(); document.querySelectorAll('[data-view]').forEach((button) => button.addEventListener('click', () => showView(button.dataset.view))); $('#profile-select').addEventListener('change', (event) => { state.data.activeProfileId=event.target.value; saveData(); renderTasks(); renderNumbers(); renderParent(); }); $('#recalculate').addEventListener('click', renderParent); $('#preview-week').addEventListener('click', () => renderPrintSheet(true)); $('#print-week').addEventListener('click', printWeek); $('#export-data').addEventListener('click', exportData); $('#import-data').addEventListener('change', importData); $('#reset-data').addEventListener('click', resetData); }
init();

